-- Tự động dọn dẹp các bảng cũ nếu đã tồn tại để tránh lỗi "already exists"
DROP TABLE IF EXISTS payments, password_reset_requests, subscriptions, chat_messages, chat_sessions, favorites, reviews, order_items, orders, vouchers, product_variants, products, categories, addresses, shops, users CASCADE;

-- Bật extension uuid-ossp để hỗ trợ tạo UUID tự động (chuẩn của Supabase)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ==============================================================================
-- 1. BẢNG USERS (Người dùng)
-- ==============================================================================
CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL, -- Đổi từ password_hash thành password để khớp với Backend
    phone VARCHAR(20),
    avatar TEXT,                    -- Đổi từ avatar_url thành avatar để khớp với Backend
    role VARCHAR(50) DEFAULT 'customer', -- 'customer', 'admin', 'shipper', 'seller'
    membership_type VARCHAR(50) DEFAULT 'normal', -- 'normal', 'vip'
    vip_expire_at TIMESTAMP WITH TIME ZONE,       -- Thêm trường gia hạn VIP
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ==============================================================================
-- 2. BẢNG SHOPS (Cửa hàng - dành cho Seller)
-- ==============================================================================
CREATE TABLE shops (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id UUID REFERENCES users(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    logo_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ==============================================================================
-- 3. BẢNG ADDRESSES (Sổ địa chỉ)
-- ==============================================================================
CREATE TABLE addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    full_name VARCHAR(255) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    address TEXT NOT NULL,
    is_default BOOLEAN DEFAULT false
);

-- ==============================================================================
-- 4. BẢNG CATEGORIES (Danh mục sản phẩm)
-- ==============================================================================
CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
    name VARCHAR(255) NOT NULL,
    image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ==============================================================================
-- 5. BẢNG PRODUCTS (Sản phẩm)
-- ==============================================================================
CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT REFERENCES categories(id) ON DELETE CASCADE,
    shop_id BIGINT REFERENCES shops(id) ON DELETE CASCADE, -- Liên kết với shop
    name VARCHAR(255) NOT NULL,
    description TEXT,
    price DECIMAL(12, 2) NOT NULL,
    vip_price DECIMAL(12, 2),
    image TEXT,
    -- ========== METADATA DÀNH RIÊNG CHO SÁCH ==========
    author VARCHAR(255),              -- Tác giả
    publisher VARCHAR(255),           -- Nhà xuất bản
    published_year INT,               -- Năm xuất bản
    isbn VARCHAR(50),                 -- Mã sách ISBN
    pages INT,                        -- Số trang
    language VARCHAR(50) DEFAULT 'Tiếng Việt', -- Ngôn ngữ
    cover_type VARCHAR(50),           -- Loại bìa: 'Bìa mềm', 'Bìa cứng', 'Bìa da'
    -- ====================================================
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ==============================================================================
-- 6. BẢNG PRODUCT_VARIANTS (Biến thể sản phẩm - đổi tên từ variants để khớp backend)
-- ==============================================================================
CREATE TABLE product_variants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
    size VARCHAR(50),
    color VARCHAR(50),
    price DECIMAL(12, 2), 
    stock INT DEFAULT 0,
    image_url TEXT
);

-- ==============================================================================
-- 7. BẢNG VOUCHERS (Mã khuyến mãi)
-- ==============================================================================
CREATE TABLE vouchers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) UNIQUE NOT NULL,
    discount_percent INT, 
    discount_amount DECIMAL(12, 2), 
    min_order_value DECIMAL(12, 2), 
    max_discount DECIMAL(12, 2), 
    usage_limit INT, 
    used_count INT DEFAULT 0, 
    is_active BOOLEAN DEFAULT true,
    expiry_date TIMESTAMP WITH TIME ZONE
);

-- ==============================================================================
-- 8. BẢNG ORDERS (Đơn hàng)
-- ==============================================================================
CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    shipper_id UUID REFERENCES users(id) ON DELETE SET NULL,
    address_id BIGINT REFERENCES addresses(id) ON DELETE SET NULL,
    status VARCHAR(50) DEFAULT 'pending', 
    payment_method VARCHAR(50) DEFAULT 'cod', 
    voucher_code VARCHAR(50),
    discount_amount DECIMAL(12, 2) DEFAULT 0,
    shipping_fee DECIMAL(12, 2) DEFAULT 0,
    total_amount DECIMAL(12, 2) DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ==============================================================================
-- 9. BẢNG ORDER_ITEMS (Chi tiết đơn hàng)
-- ==============================================================================
CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
    variant_id BIGINT REFERENCES product_variants(id) ON DELETE SET NULL, -- Liên kết với product_variants
    quantity INT DEFAULT 1,
    price DECIMAL(12, 2) NOT NULL 
);

-- ==============================================================================
-- 10. BẢNG REVIEWS (Đánh giá)
-- ==============================================================================
CREATE TABLE reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
    order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
    rating INT CHECK (rating >= 1 AND rating <= 5),
    comment TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ==============================================================================
-- 11. BẢNG FAVORITES (Yêu thích)
-- ==============================================================================
CREATE TABLE favorites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ==============================================================================
-- 12. BẢNG CHAT_SESSIONS (Phiên chat)
-- ==============================================================================
CREATE TABLE chat_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id UUID REFERENCES users(id) ON DELETE CASCADE,
    last_message TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ==============================================================================
-- 13. BẢNG CHAT_MESSAGES (Tin nhắn)
-- ==============================================================================
CREATE TABLE chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT REFERENCES chat_sessions(id) ON DELETE CASCADE,
    sender_id UUID REFERENCES users(id) ON DELETE CASCADE,
    receiver_id UUID REFERENCES users(id) ON DELETE CASCADE,
    sender_role VARCHAR(50), 
    message TEXT NOT NULL,
    is_read BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ==============================================================================
-- 14. BẢNG SUBSCRIPTIONS (Đăng ký gói VIP)
-- ==============================================================================
CREATE TABLE subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    plan_name VARCHAR(255) NOT NULL,
    amount DECIMAL(12, 2) NOT NULL,
    start_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    end_date TIMESTAMP WITH TIME ZONE,
    status VARCHAR(50) DEFAULT 'active',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ==============================================================================
-- 15. BẢNG PASSWORD_RESET_REQUESTS (Yêu cầu quên mật khẩu)
-- ==============================================================================
CREATE TABLE password_reset_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES users(id) ON DELETE SET NULL,
    email VARCHAR(255) NOT NULL,
    full_name VARCHAR(255),
    phone VARCHAR(20),
    status VARCHAR(50) DEFAULT 'pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ==============================================================================
-- 16. BẢNG PAYMENTS (Lịch sử thanh toán - nếu shipper.js cần)
-- ==============================================================================
CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
    amount DECIMAL(12, 2) NOT NULL,
    payment_method VARCHAR(50),
    status VARCHAR(50) DEFAULT 'success',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ==============================================================================
-- TRIGGER CẬP NHẬT TRƯỜNG `updated_at` TỰ ĐỘNG
-- ==============================================================================
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_products_updated_at
    BEFORE UPDATE ON products
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_orders_updated_at
    BEFORE UPDATE ON orders
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_chat_sessions_updated_at
    BEFORE UPDATE ON chat_sessions
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_shops_updated_at
    BEFORE UPDATE ON shops
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ==============================================================================
-- SEED DATA — DỮ LIỆU KHỞI TẠO MẶC ĐỊNH
-- ==============================================================================

-- 1. Tạo Shop hệ thống mặc định (shop_id = 1, backend admin dùng mặc định)
--    Lưu ý: Cần có ít nhất 1 user admin trước khi chạy dòng này.
--    Nếu chưa có user, hãy bỏ qua phần này và tạo shop sau.
-- INSERT INTO shops (owner_id, name, description)
-- VALUES ('<UUID_CỦA_ADMIN>', 'BookHaven Official Store', 'Cửa hàng sách chính thức');

-- 2. Seed danh mục sách (10 thể loại phổ biến)
INSERT INTO categories (name) VALUES
  ('Văn học - Tiểu thuyết'),
  ('Khoa học - Công nghệ'),
  ('Kỹ năng sống'),
  ('Thiếu nhi - Truyện tranh'),
  ('Lịch sử - Địa lý'),
  ('Kinh tế - Kinh doanh'),
  ('Tâm lý học'),
  ('Giáo khoa - Tham khảo'),
  ('Ngoại ngữ'),
  ('Nghệ thuật - Sáng tạo');
